#!/bin/bash
#PBS -q workq
#PBS -N lattice_tournament
#PBS -P PR350
#PBS -o /home/c1569433/src/jobs/stdout.txt
#PBS -e /home/c1569433/src/jobs/stderr.txt
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -l place=scatter:excl
#PBS -l walltime=70:00:00

#PROJECT=PR350

alias python='~/anaconda3/bin/python'

export MPLBACKEND="agg"
# Run a spatial tournament with a newman watts strogatz topology
cd /home/c1569433/src/jobs/scripts
python lattice.py
