#!/bin/bash
#PBS -q workq
#PBS -N lattice_shuffling_players_tournament
#PBS -P PR350
#PBS -o /home/c1569433/src/jobs/stdout.txt
#PBS -e /home/c1569433/src/jobs/stderr.txt
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -l place=scatter:excl
#PBS -l walltime=70:00:00

#PROJECT=PR350

export MPLBACKEND="agg"
# Run a spatial tournament with a cycle topology
cd /home/c1569433/src/jobs/scripts
~/anaconda3/bin/python Simple_topology_Lattice.py
